version: '3.8'

services:
  gym-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fitlife-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - fitlife-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 30s

  gym-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: fitlife-frontend
    ports:
      - "3000:80"
    depends_on:
      - gym-backend
    networks:
      - fitlife-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: fitlife-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fitlife-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data:

networks:
  fitlife-network:
    driver: bridge